{% set name = "cysgp4" %}
{% set version = "0.3.3" %}
{% set sha256 = "76c83ee090cd097248c18bbbebe6891288e9b8e6185292ab8e7893f3492aac66" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [py27]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - openmp 4.0.*  # [osx]
    - python
    - pip
    - setuptools
    - setuptools_scm
    - cython
    - numpy

  run:
    - python
    - setuptools
    - openmp 4.0.*  # [osx]
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cysgp4

  commands: python -c "import cysgp4; cysgp4.test()"

about:
  home: https://github.com/bwinkel/{{ name }}
  license: GPL-3.0 AND Apache-2.0 AND BSD-3-Clause
  license_file:
    - COPYING.GPLv3.txt
    - COPYING.Apache2
    - TEMPLATE_LICENCE.rst
  summary: Cysgp4 is a wrapper around the SGP4 package, for sat TLE calculations
  description: |
    The cysgp4 package is a Cython-powered wrapper of the sgp4 C++ library
    by Daniel Warner to compute satellite positions from two-line elements
    (TLE). It provides similar functionality as the well-known sgp4 Python
    package by Brandon Rhodes, which uses Numba internally to speed-up the
    calculations. In contrast to sgp4, cysgp4 can work well with arrays of
    TLEs and/or times and make use of multi-core platforms (via OpenMP) to
    boost processing times a lot.
  dev_url: https://github.com/bwinkel/{{ name }}

extra:
  recipe-maintainers:
    - bwinkel
